// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_ubqByLGteSmcDOx74v2u9lokUTicpE',
    appId: '1:15817683189:web:85ceaf0d4e98acbd6bd5bc',
    messagingSenderId: '15817683189',
    projectId: 'comusesign',
    authDomain: 'comusesign.firebaseapp.com',
    databaseURL: 'https://comusesign.firebaseio.com',
    storageBucket: 'comusesign.appspot.com',
    measurementId: 'G-QHSKZ3G49S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmV1s_YYjyBqJyzA2NrDZ9JTFUDk1-GQk',
    appId: '1:15817683189:android:c9f6dd41900baf886bd5bc',
    messagingSenderId: '15817683189',
    projectId: 'comusesign',
    databaseURL: 'https://comusesign.firebaseio.com',
    storageBucket: 'comusesign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRc-Pd_e5X7fXB0vnsAWe_wmASaZNzag',
    appId: '1:15817683189:ios:b3979dc17847ad8f6bd5bc',
    messagingSenderId: '15817683189',
    projectId: 'comusesign',
    databaseURL: 'https://comusesign.firebaseio.com',
    storageBucket: 'comusesign.appspot.com',
    androidClientId: '15817683189-ag68uo70c93k479b3vmudlh407o9dbv4.apps.googleusercontent.com',
    iosClientId: '15817683189-8geum2d1kj6l1i64bpgdq1e8ro7jppd6.apps.googleusercontent.com',
    iosBundleId: 'com.comuse.comuse',
  );
}
